[project]
name = "secure-data-encryption-system"
version = "0.1.0"
description = "A secure data encryption system using Streamlit and cryptography"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "streamlit>=1.44.1",
    "cryptography>=39.0.0"
]
